### ISSUE TITLE
API request can kill the server?

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/disaster-asset-manager#14]
using the "_id" property returns the file. using the "file_ids" property terminates the server with the following logged to the terminal:

```
/Users/danbjoseph/Documents/Github/AmericanRedCross/disaster-asset-manager/routes/app.js:380
            ctrl.gfs.files.find({filename:asset.file}).toArray(function(err,files) {
                                               ^
TypeError: Cannot read property 'file' of null
    at /Users/danbjoseph/Documents/Github/AmericanRedCross/disaster-asset-manager/routes/app.js:380:39
    at /Users/danbjoseph/Documents/Github/AmericanRedCross/disaster-asset-manager/node_modules/mongoose/lib/query.js:1174:16
    at /Users/danbjoseph/Documents/Github/AmericanRedCross/disaster-asset-manager/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at process._tickCallback (node.js:355:11)
» 
```

**Comment by kevinlustig** [comment]
This issue has been resolved - the getAssetFile routine was not well suited to handle anything except a valid asset ID. It's now more robust. 

Note that the ID in the _id property for an asset is the ID of that asset, whereas the IDs in the file_ids array, file property, thumbnail property, etc. are IDs for associated files. The API functions rely _only_ on the ID for the asset itself - you're basically saying "Give me the file/thumbnail associated with the asset identified by the ID" **not** "Give me the file/thumbnail identified by the ID." Instead of interrupting the whole server process, doing the latter will now just get you a 404.
